#!/usr/bin/ruby
# Simple script to download mp3s from an RSS feed

require 'yaml'
require 'nokogiri'
require 'open-uri'

# Pull in our configuration
config = YAML.load_file('config.yaml')


Dir.chdir(config['music_dir']) do
  # Pull down the RSS feed
  feed = Nokogiri::XML(open(config['rss_feed']))

  # Find any new files and download them
  feed.css('item enclosure').each do |item|
puts item.inspect
    filename = File.basename(item['url'])
  
    unless File.exist?(filename)
      puts "Downloading #{filename}"
      `wget --quiet '#{item['url']}'`
    else
      puts "Already got #{filename}"
    end
  end
end

