#!/usr/bin/ruby
# Simple script to download mp3s from an RSS feed

require 'yaml'
require 'simple-rss'
require 'open-uri'

# Pull in our configuration
config = YAML.load_file('config.yaml')


Dir.chdir(config['music_dir']) do
  # Pull down the RSS feed
  feed = SimpleRSS.parse(open(config['rss_feed']))

  # Find any new files and download them
  feed.items.each do |item|
    filename = File.basename(item.media_content_url)
  
    unless File.exist?(filename)
      puts "Downloading #{filename}"
      `wget --quiet '#{item.media_content_url}'`
    else
      puts "Already got #{filename}"
    end
  end
end

